*** Variables ***
${usuarioSAP}                  CO_HITSS
${claveSAP}                    Noviembre*2016
${transaccionMB52}             MB52
${transaccionME21N}            ME21N
${transaccionVL10B}            VL10B
${transaccionVL02N}            VL02N
${transaccionIQ09}             IQ09
# TransaccionME21N
${lote}                        VALORADO
${almacen}                     H001
${pedidoTraslado}              PEDIDO DE TRASLADO
# TransaccionISQ09
${statusInclusivoIsq09}        ALMA